### ISSUE TITLE
SNS notification for soca's job status

### ISSUE THREAD

**Issue by wttat** [awslabs/scale-out-computing-on-aws#102]
**Is your feature request related to a problem? Please describe.**

When a job is done, i want to receive notification via sns instead of manully check via the soca's console, soca only support ses at this time , however, ses need remove sandbox and it does support all aws regions like (cn-north-1 or cn northwest-1)
**Describe the feature you'd like**
intregate the sns topic/sub  function into soca's console, let soca user easily choose to sub a topic and receive soca's job's status by email or other.
**Additional context**
although i can manully write a aws cli to call sns's api via into %user_post_exec%, it would be nice if it could be configure via webui.

**Comment by mcrozes** [comment]
Hello @wttat  -

Is this feature still a requirement? As you said, you can currently script this directly in the post-routine. The challenge (if we deploy this feature natively) would be to ensure the SNS topic permissions are locked to only a given of user/IAM role.

Happy to discuss more -

**Comment by mcrozes** [comment]
Closed. Feel free to re-open if this is still needed.
