### ISSUE TITLE
User/groups management not working via web UI

### ISSUE THREAD

**Issue by mission-coliveros** [awslabs/scale-out-computing-on-aws#104]
A new issue has popped up for us, where none of our admin users can manage users/groups via the web interface.

When loading the Admin/Users tab, we get an internal server error, detailed below:
`The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

When loading the Admin/Groups tab, the page loads, but we get the following error message at the top of the page:
`Unable to list groups: b'{"success": false, "message": "Invalid user credentials."}\n'`

I'm pretty sure these are both the same issue, but the users.py script isn't handling the exception properly.

Any idea why this might be happening?

**Comment by mcrozes** [comment]
Closing issue as the last update was over 3 months ago. Feel free to re-open if needed.
