### ISSUE TITLE
SOCA scheduler sporadically falling out of Active Directory

### ISSUE THREAD

**Issue by mission-coliveros** [awslabs/scale-out-computing-on-aws#108]
## Describe the bug
While running a relatively standard install of SOCA (filesystems, compute, and directory are all created by SOCA CDK stack), the scheduler node is sporadically falling off of the Active Directory, forcing us to leave the realm and rejoin, with the following script:

```bash
CLUSTER_NAME=soca-example

# Setup AWS CLI and retrieve SOCA secret
export AWS_DEFAULT_REGION=us-east-1
secret=$(aws secretsmanager get-secret-value --secret-id $CLUSTER_NAME --query SecretString --output text)

# Parse relevant variables from secret value
DS_DOMAIN_NAME=$(echo "$secret" | jq .DSDomainName | tr -d '"')
UPPER_DS_DOMAIN_NAME=$(echo "$DS_DOMAIN_NAME" | tr a-z A-Z)
DS_DOMAIN_ADMIN_USERNAME=$(echo "$secret" | jq .DSDomainAdminUsername | tr -d '"')
DS_DOMAIN_ADMIN_PASSWORD=$(echo "$secret" | jq .DSDomainAdminPassword | tr -d '"')

# Backup existing sssd.conf
sudo cat /etc/sssd/sssd.conf
sudo cp /etc/sssd/sssd.conf /etc/sssd/sssd.conf.backup

# Remove computer from realm, leave then rejoin
echo "${DS_DOMAIN_ADMIN_PASSWORD}" | sudo realm leave \
  --user "${DS_DOMAIN_ADMIN_USERNAME}" "${UPPER_DS_DOMAIN_NAME}" \
  --verbose

echo "${DS_DOMAIN_ADMIN_PASSWORD}" | sudo realm join \
  --user "${DS_DOMAIN_ADMIN_USERNAME}" "${UPPER_DS_DOMAIN_NAME}" \
  --verbose

# Restart sssd
sudo mv /etc/sssd/sssd.conf.backup /etc/sssd/sssd.conf
sudo systemctl restart sssd
sudo systemctl status sssd
```

We can pretty reliably resolve the issue when it comes up by running this script, but we've so far been unsuccessful at identifying the root cause of the issue.

## To Reproduce
The issue is sporadic, and we cannot currently reproduce the issue.  I'm wondering if this might stem from the hostname being truncated when joining the directory.

## Please complete the following information about the solution
- Version: `2.7.4`
- Region: `us-east-1`
- Was the solution modified from the version published on this repository?: `No`
- Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?: `Yes`
- Were there any errors in the CloudWatch Logs?: `No`

## Additional context
When checking the status of the `sssd` service, we often see the following error before restarting:
```
Unspecified GSS failure. Minor code may provide more information Server not found in Kerberos database
``` 

One idea I had was to change the hostname of the scheduler, as the CDK stack uses ip addresses instead of instance IDs for hostnames.  This results in the name of the AD computer to be truncated from `IP-10-100-12-233` to `IP-10-100-12-23`, which may be resulting in the occasional overlap when a new instance with the IP of `IP-10-100-12-23*` joins the realm.

**Comment by mcrozes** [comment]
Hey @mission-coliveros -

Thanks for reporting this. This issue has been addressed on IDEA, so we need to see if we can backport it to SOCA.

**Comment by mcrozes** [comment]
This should have been addressed as part of our last update: https://github.com/awslabs/scale-out-computing-on-aws/blob/main/source/soca/cluster_node_bootstrap/bootstrap.d/active_directory.sh#L32-L35
