### ISSUE TITLE
bug in install_soca.py line 215  (regex check logic)

### ISSUE THREAD

**Issue by tammy-ruby-cherry** [awslabs/scale-out-computing-on-aws#113]
**Describe the bug**
install_soca.py line 215:    the "not" shouldn't be there.  As written, the bucket name is rejected if it does not match the regex.
```
 if not re.match(_s3_bucket_re, bucket):
        print(f"[red]Invalid S3 bucket name: ({bucket}). Must match Regular Expression: {_s3_bucket_re}[/red]")
        return False
```
 

**To Reproduce**
run the installer 

**Expected behavior**
Hmm....I guess ... _not_ to reject a valid bucket name?  (Sorry, couldn't resist. Bad impulse control at the end of the workday. )

**Please complete the following information about the solution:**
- [ ] Version: **2.7.5**

- [ ] Region: **eu-west-1**
- [ ] Was the solution modified from the version published on this repository?  **n/a**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?  **n/a**
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the _sevices_ this solution uses?      **n/a  (Probably a good idea to fix the typo in "sevices", though)**
- [ ] Were there any errors in the CloudWatch Logs? **n/a**

**Comment by jsynack** [comment]
Hello,

Do you have a bucket name example that is not matching the RE that you think should be matching / permitted based on the S3 bucket naming restrictions? (https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html)

**Comment by tammy-ruby-cherry** [comment]
rc3.bucket

**Comment by jsynack** [comment]
Thanks!

Per the code snip - dots are not allowed in the buckets:

```
    # Check bucket naming before sending to the API
    # Rules are based on: https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
    # NOTE - if the bucket requires a dot (.) - modify the regex
    _s3_bucket_re = r'(?!(^(xn--|sthree-|sthree-configurator)|.+(-s3alias|--ol-s3)$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$'
```

The reason for this is spelled out at the URL:

```
Buckets used with Amazon S3 Transfer Acceleration can't have dots (.) in their names. For more information about Transfer Acceleration, see [Configuring fast, secure file transfers using Amazon S3 Transfer Acceleration](https://docs.aws.amazon.com/AmazonS3/latest/userguide/transfer-acceleration.html).
```

and

```
For best compatibility, we recommend that you avoid using dots (.) in bucket names, except for buckets that are used only for static website hosting. If you include dots in a bucket's name, you can't use virtual-host-style addressing over HTTPS, unless you perform your own certificate validation. This is because the security certificates used for virtual hosting of buckets don't work for buckets with dots in their names.
```

If this is an acceptable tradeoff - you can modify the regex to allow the `.`   . Since it is not a recommendation - it is default denied.

**Comment by mcrozes** [comment]
Closed as discussed via email.
