### ISSUE TITLE
CST Studio can't acess (FlexNet Licensing error:-39, 147)

### ISSUE THREAD

**Issue by hyungryong** [awslabs/scale-out-computing-on-aws#118]
When I access to CST studio 202x with Licensing option selecting Point to an existing Flexnet-based CST..., it failed in below message.

User/host not on INCLUDE list for feature.
Feature: start
License path: 6000@dt-license1.aka.amazon.com;
FlexNet Licensing error:-39, 147

<img width="1698" alt="Screenshot 2024-05-22 at 22 16 03" src="https://github.com/awslabs/scale-out-computing-on-aws/assets/170584029/23703d33-5cc8-496e-bd30-dec3c1cf4985">

**Comment by mcrozes** [comment]
Hello,

Please note this Github is not for internal support. I will forward your request to your internal SOCA support team.
