### ISSUE TITLE
cluster_logs_management/send_logs-s3.sh -- add region to aws s3 sync commands

### ISSUE THREAD

**Issue by tammy-ruby-cherry** [awslabs/scale-out-computing-on-aws#119]
**Describe the bug**
AWS_DEFAULT_REGION / region of S3_BUCKET incompatibility raises error when the cluster_logs_management/send_logs_s3.sh runs

Error message:
`download failed: s3://XXXXXX/soca-YYYYY/ An error occurred (IllegalLocationConstraintException) when calling the GetObject operation: The eu-central-1 location constraint is incompatible for the region specific endpoint this request was sent to.`

**To Reproduce**
My bucket is in eu-central-1; SOCA is in il-central-1.  The il-central-1 region uses region-specific endpoints.  I imagine the same error would happen when there is a similar bucket-region/soca-region incompatibility and the soca-region in the account uses region specific endpionts

**Please complete the following information about the solution:**
- [ ] Version: 2.7.5

- [ ] Region: il-central-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? NO
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?  (<--there's still a typo in "**sevices**").  N/A
- [ ] Were there any errors in the CloudWatch Logs? N/A

**Bug fix**
Modify the code as follows:

```
S3_BUCKET="s3://$SOCA_INSTALL_BUCKET/$SOCA_CONFIGURATION/cluster_logs/"
S3_BUCKET_REGION=$(aws s3api get-bucket-location --bucket $SOCA_INSTALL_BUCKET --output text)
.
.
.
/usr/bin/aws s3 sync $SCHEDULER_SERVER_LOGS $S3_BUCKET'server_logs/' --region $S3_BUCKET_REGION
/usr/bin/aws s3 sync $SCHEDULER_SCHED_LOGS $S3_BUCKET'sched_logs/'  --region $S3_BUCKET_REGION
/usr/bin/aws s3 sync $COMPUTE_HOST_LOG $S3_BUCKET'compute_host_logs/'  --region $S3_BUCKET_REGION
```

**Comment by mcrozes** [comment]
Thanks @tammy-ruby-cherry  for the report and proposed change.

As we are in the process of refreshing this section, I'd like to know if sending these logs to CloudWatch (via LogAgent) would make sense to you?

**Comment by mcrozes** [comment]
Closing ticket. Changes have been made to the internal repo and will be made available publicly on the next release.
