### ISSUE TITLE
Issue with Creating soca-jobs* Index for SOCA Dashboard

### ISSUE THREAD

**Issue by wbadyx** [awslabs/scale-out-computing-on-aws#129]
Hello,

On the SOCA web page under "My Activity," I am getting the following message:
"Unable to retrieve index ID for soca-jobs*. To do the initial setup, follow instructions available on https://awslabs.github.io/scale-out-computing-on-aws/analytics/monitor-cluster-activity/"

However, when I follow the instructions in the documentation, I am unable to create the soca-jobs* index. Instead, I can only create the soca_jobs* index, which results in the Dashboard not displaying correctly.

Version: OpenSearch 2.11

Thank you for your help.

**Comment by mcrozes** [comment]
Context: https://github.com/awslabs/scale-out-computing-on-aws/discussions/128 

Index are not retrieved correctly when using OpenSearch. OpenSearch is still fully operational and can be accessed via the OpenSearch dashboard URL, however, reporting from the SOCA console is currently broken.

Fix: Query OpenSearch API to returns the list of index. This is a low priority task as there is currently a workaround, and I'm planning to fix that in the upcoming release for Q3 this year. Let me know if you need to expedite this before.
