### ISSUE TITLE
Launch a job with FSx for Lustre is failed

### ISSUE THREAD

**Issue by wbadyx** [awslabs/scale-out-computing-on-aws#130]
**Describe the bug**
Launch a job with FSx for Lustre is failed
`qsub -l fsx_lustre=s3://soca-wba-demo/ -N job s.sh`

Error Info:
`str object has no attribute keys : error:<class AttributeError > add nodes.py 814 { error message : str object has no attribute keys : error:<class AttributeError >`

- [ ] Region: [e.g. us-east-1]

**Screenshots**

![soca_20240715143847](https://github.com/user-attachments/assets/fcd6c7b0-bd93-412b-b8df-850349add8f1)

**Comment by mcrozes** [comment]
Hello, 

Please remove the trailing `/` at the end of your bucket name as it will triggers a regex error

```
bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

I was able to reproduce your error using `s3://<bucket>/` and confirmed `s3://<bucket>` is working ok.

Can you please give it a try and let me know.

With that said, +1 on adding better logging reporting, I'm working on a new logging framework for the next version.

**Comment by wbadyx** [comment]
I encountered an error when running the qsub command:
`qsub -l fsx_lustre=s3://soca-wba-demo -N job s.sh`
The error message was: At most 1 subnet is allowed.

To resolve this, I specified a subnet ID, and the command worked:
`qsub -l subnet_id=subnet-0469f80ffec266849,fsx_lustre=s3://soca-wba-demo -N job s.sh`
Thank you for your help.
