### ISSUE TITLE
qsub -V env vars are no longer inherited after upgrade to PBS 23.06.06

### ISSUE THREAD

**Issue by gmc99** [awslabs/scale-out-computing-on-aws#138]
Hi,

We're in the process of upgrading to SOCA 275 but qsub jobs are failing as they are not inheriting the environment variables from the submit process.
The working nodes ran C7/RHEL8 with PBS 20.0.1
The failing nodes are running RHEL8 with PBS 23.06.06

If I send a job 'qsub -V run.sh' and look at 'qstat -f' the working node shows me a Variable_List which includes all the env vars from the submit process - the failing node only contains ~8 PBS_O_* variables.

I can submit 'qsub -v VAR1=TEST' and see the variable being inherited - it's impracticable to do this for all environments because of the number of environment variables in the submit process.

thanks

**Comment by mcrozes** [comment]
Hey @gmc99 -

Would you be interested to test the new version we are almost ready to ship? It would be interesting to see if you can upgrade directly as this version will replace 2.7.5 soon. Additionally we can verify if the env variables are processed correctly.

Feel free to email aligo@amazon.com if you want to beta test.

**Comment by gmc99** [comment]
Hi
if you want to get this running ahead of the new update look at this thread -
https://community.openpbs.org/t/qsub-v-env-vars-not-exported-after-upgrade/3993

Find the two files in this pull request and update them, when PBS is built in the AMI/node it will fix this issue - no need to rebuild the server.

https://github.com/openpbs/openpbs/pull/2602/commits/9ea88efb20df0f510fb5bf8f1a16e235583c8d3a
