### ISSUE TITLE
IAM Role Policy error

### ISSUE THREAD

**Issue by seecsea** [awslabs/scale-out-computing-on-aws#139]
**Describe the bug**
cannot create IAM Policy with installer/SOCAInstallerIamPolicy.json

**Please complete the following information about the solution:**
- [ ] Version: [e.g. v2.7.5]

- [ ] Region: [e.g. us-west-2]

**Screenshots**
Ln 215, Col 16 | Invalid Action: The action es:CreateServiceLinkedRole does not exist.

**Comment by mcrozes** [comment]
Hello,

Good catch. This rule has been removed from our staging code and will be updated on Github in the coming weeks.
