### ISSUE TITLE
v2.7.5(There is a bug in connecting to opensearch)

### ISSUE THREAD

**Issue by ZDYC** [awslabs/scale-out-computing-on-aws#142]
1. /apps/soca/soca-49022/cluster_analytics/cluster_nodes_tracking.py, Line 69 errror,

Missing headers={'Content-Type': 'application/json'},

1. This will cause opensearch to report an error and the index cannot be created.

```
**def build_client(engine):
    try:
        if engine == 'opensearch':
            return OpenSearch(
                [os_endpoint],
                http_auth=awsauth,
                use_ssl=True,
                verify_certs=True,
                ssl_assert_hostname=False,
                ssl_show_warn=False,
                connection_class=RequestsHttpConnection,
            )
        else:
            return Elasticsearch([os_endpoint],
                               port=443,
                               http_auth=awsauth,
                               use_ssl=True,
                               verify_certs=True,
                               connection_class=RequestsHttpConnection)
```

<img width="456" alt="截屏2024-10-25 11 33 56" src="https://github.com/user-attachments/assets/7b0e66f8-cd35-45a4-9c2c-91109e21ffb0">

**Comment by mcrozes** [comment]
Hello @ZDYC and thanks for contributing to SOCA.

We have pushed a new version yesterday which address this bug. We also have revamped the analytics module and created a new `SocaAnalyticsClient` class.  Headers can be defined dynamically and will default to `{'Content-Type': 'application/json'}` https://github.com/awslabs/scale-out-computing-on-aws/blob/main/source/soca/cluster_manager/utils/analytics_client.py#L89
