### ISSUE TITLE
v2.7.5 Metricbeat does not support opensearch. How should we monitor the performance of tasks and ec2?

### ISSUE THREAD

**Issue by ZDYC** [awslabs/scale-out-computing-on-aws#143]
<img width="741" alt="截屏2024-10-25 11 36 21" src="https://github.com/user-attachments/assets/d89d51e7-fbd6-43e7-8f12-38a5816f0497">

Please!
Metricbeat does not support opensearch. How should we monitor the performance of soca_jobs and ec2(such as cpu)? like this
![Uploading WechatIMG1564.jpg…]()

**Comment by mcrozes** [comment]
Hello @ZDYC  -

You could possibly use CloudWatch to get host level metrics, or leverage https://aws.amazon.com/grafana/ (or any existing Grafana environment).

What information would you like to monitor? Would you be interested in a native support for Grafana (probably via `SocaAnalyticsClient` provider)?
