### ISSUE TITLE
When starting a job, why is the ec2 configuration always c6i.large？The EC2 model entered on the front-end page cannot be recognized

### ISSUE THREAD

**Issue by ZDYC** [awslabs/scale-out-computing-on-aws#144]
Dear,
  When I configured the PBS+StarCCM application, 
  I found that no matter how I chose the EC2 model on the front-end, 
   the machine I started was always c6i.large, and I wanted to know if it was a code bug.thanks!,
   
Example：
<img width="573" alt="截屏2024-11-06 13 10 44" src="https://github.com/user-attachments/assets/2c752c12-51f9-46cf-a23a-1798bf9a3217">
I adjusted the EC2 model to c6i.2xlarge, the required CPU is 16, and 2*c6i.2xlarge should be started in the background. 
But the actual startup was 8*c6i.large

**Comment by ZDYC** [comment]
I adjusted the EC2 model to c6i.2xlarge, the required CPU is 16, 
and 2*c6i.2xlarge should be started in the background.
But the actual startup was 8*c6i.large

**Comment by sysdori** [comment]
Hi, ZDYC
Did you set up "Application Management -> 'What type of instance do you want to use? (instance_type)'" as an administrator? This picture is the EC2 selection screen for the web application used in fluent.

In my case, after completing the SW tile in "Application management", the number of nodes for the selected instance was automatically calculated when the user selected the instance type and entered the number of cores.
![selectInstanceType](https://github.com/user-attachments/assets/7484798e-8497-4597-8b05-9fdf7fbe36f6)

![image](https://github.com/user-attachments/assets/a6ef77ad-3f21-4dc5-a83a-5842014e7436)

**Comment by ZDYC** [comment]
the code version v2.7.5

**Comment by mcrozes** [comment]
Hello @ZDYC -

Can you export your application profiles and send the .json to my Github Username @amazon.com 

As Admin User, login to Web Interface > Application Management > Import/Export tab

**Comment by ZDYC** [comment]
My problem has been solved, thanks
