### ISSUE TITLE
Password for 3D session

### ISSUE THREAD

**Issue by oniyamazon** [awslabs/scale-out-computing-on-aws#22]
Hello, 

I realized that I needed a password to unlock a 3D session that I launched. I used license file authentication for GUI access using putty, so I don't have the password. 

If I need to use SOCA console, that website is not working for me (503 Service Temporarily Unavailable).

Thank you,

Tomo Oniyama

**Comment by mcrozes** [comment]
Hey Tomo -

Since your are using our internal cluster, I am moving this support request to our internal tracking system.
