### ISSUE TITLE
DCV-GL fails in 3D desktop sessions

### ISSUE THREAD

**Issue by bollig** [awslabs/scale-out-computing-on-aws#23]
Environment: default launch of SOCA v2.0.1 in us-east-1 using https://aws.amazon.com/solutions/implementations/scale-out-computing-on-aws/ . 
OS: alinux

Problem: Quick Launch 3D sessions open remote desktop, but DCV does not have GL enabled. Open a terminal and run `nvidia-smi -L` shows that the GPUs (4x M60s) are present, but command `glxgears` does not work. `sudo dcvgldiag` reports missing rpms and bad configuration in xorg.conf. 

Temporary fix: 
1. ssh to cluster master, and then ssh to the compute node running the desktop. Running the following commands will NOT work in the remote desktop, and once you restart the dcv services, the sessions are killed. 
2. `dcv list-sessions` (make note of the uuid for the session-id printed here; e.g., 56687e00-081e-4ad1-9990-05316cd26899)
3. `sudo yum install xorg-x11-server-Xorg xorg-x11-server-utils xorg-x11-utils`
4. `sudo nvidia-xconfig --enable-all-gpus`
5. `sudo systemctl restart dcv* gdm*`
6. `dcv create-session 56687e00-081e-4ad1-9990-05316cd26899 --gl on` (this session-id must exactly match the session-id above, or the SOCA portal will not be able to reconnect you to the remote desktop). 

![image](https://user-images.githubusercontent.com/187202/84464953-76899f00-ac3b-11ea-9c70-6102735da2f7.png)

**Comment by mcrozes** [comment]
Hey Evan -
I added you to the discussion group to discuss this issue and provide a fix.

**Comment by mcrozes** [comment]
I updated `scripts/config.cfg` to include the missing `x11` packages

Before:

![Screen Shot 2020-06-12 at 7 36 00 PM](https://user-images.githubusercontent.com/1182095/84554898-1dc41000-ace8-11ea-9dd8-9e5a27b86f58.png)

Now:
<img width="1027" alt="Screen Shot 2020-06-12 at 8 04 50 PM" src="https://user-images.githubusercontent.com/1182095/84554910-303e4980-ace8-11ea-910f-31030f76154a.png">

This change will be pushed to the `2.5.0` release.

Thanks for your contribution
