### ISSUE TITLE
Missing g4dn

### ISSUE THREAD

**Issue by bollig** [awslabs/scale-out-computing-on-aws#24]
https://github.com/awslabs/scale-out-computing-on-aws/blob/258672c605d800c43b14bf422febccf60aa42cc8/source/soca/cluster_node_bootstrap/ComputeNodeInstallDCV.sh#L8

DCV does not install GPU support when instance type g4dn.12xlarge is used for desktop sessions.

**Comment by bollig** [comment]
Noticed that g4* are missing from the SOCA Graphical Access page. G4* are also are notoriously missing from: 
 
`/apps/soca/soca-socademo2/python/3.7.1/lib/python3.7/site-packages/botocore/data/ec2/2016-11-15/service-2.json`
`/apps/soca/soca-socademo2/python/3.7.1/lib/python3.7/site-packages/troposphere/constants.py`

`sudo su -`
`source /etc/environment`
`pip3 install --upgrade botocore troposphere`
`/apps/soca/soca-CLUSTER/cluster_web_ui/socawebui.sh stop && /apps/soca/soca-CLUSTER/cluster_web_ui/socawebui.sh start`

resolved the issue and now I have a current list of instance types.

**Comment by bollig** [comment]
G4dn still not installing DCV properly. Desktop opens, but no NVidia driver is installed.

**Comment by bollig** [comment]
Manually pulled G4 driver `aws s3 cp --recursive s3://ec2-linux-nvidia-drivers/g4/latest/ .` (per https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html#nvidia-GRID-driver), and installed. See https://github.com/awslabs/scale-out-computing-on-aws/blob/258672c605d800c43b14bf422febccf60aa42cc8/source/soca/cluster_node_bootstrap/ComputeNodePostReboot.sh#L22 (for g4*, the S3 URL changes to the /g4/latest/ prefix). 

`sudo dcvgladmin enable 64`
`sudo dcvgladmin enable 32`
`sudo nvidia-xconfig --enable-all-gpus`
`sudo systemctl restart dcv* gdm*`
and recreated the dcv session. Now i have a fully functional 3D session with 4 T4 GPUs.

**Comment by mcrozes** [comment]
Hey Evan -
I added you to the discussion group to discuss this issue and provide a fix.

**Comment by mcrozes** [comment]
I bumped the following packages

```
awscli==1.18.78
boto3==1.14.1
botocore==1.17.1
```

G4 instances are now listed correctly on the web ui
![g4_instances](https://user-images.githubusercontent.com/1182095/84545826-f6604980-accd-11ea-88db-8ceec8f24f18.png)

I also updated the `.sh` scripts to point to the correct nvidia drivers

![Screen Shot 2020-06-12 at 6 46 00 PM](https://user-images.githubusercontent.com/1182095/84551883-ffa4e280-acdc-11ea-9f1d-b7740528446b.png)

This fix will be pushed as part of the 2.5.0 release which is set to be release in July.

Thanks for your contribution !
