### ISSUE TITLE
504 gateway timeout error

### ISSUE THREAD

**Issue by gmc99** [awslabs/scale-out-computing-on-aws#36]
Hi,
I have a soca system that has been running for a couple of months. On Friday we tried to add a new user using the SOCA user manager, after entering the new user details, it eventually returned 502 bad gateway. Now its impossible to bring up the web UI it just returns 504 Gateway timeout.
I'm trying to debug this but need some help understanding the way it works. If I look at the load balancers they say the Scheduler is an 'unhealthy' target. I can see some monitors in the ELB's that look like the ELB's are getting the web hit but they are not able to pass it on to the scheduler. 
I can't see anything obviously wrong with the Scheduler logs - and a reboot doesn't help. 

- What process runs the webui on the Scheduler
- is it possible to access the web ui directly on the Scheduler
- what needs to be running and can I start it from a command line

thanks

**Comment by mcrozes** [comment]
Hello @gmc99 -

> What process runs the webui on the Scheduler

&
> what needs to be running and can I start it from a command line


Web UI is managed by /apps/soca/<your_cluster_id>/cluster_web_ui/socawebui.sh (https://github.com/awslabs/scale-out-computing-on-aws/blob/master/source/soca/cluster_web_ui/socawebui.sh). 
- Check if your UI is running `/apps/soca/<your_cluster_id>/cluster_web_ui/socawebui.sh  status`
- Start/Stop: `/apps/soca/<your_cluster_id>/cluster_web_ui/socawebui.sh start/stop`

> is it possible to access the web ui directly on the Scheduler

Yes, however you will need to make sure port 8443 is open on the security group for the IP you are trying to access from (by default only port 443 is open).

User --> ALB (443) ---> Web UI on scheduled (8443)

Once you have opened port  8443, you can access it via https://<ip_of_scheduler>:8443/. Note you can also test the UI from the scheduler itself by running a simple `curl https://localhost:8443 -k` command (assuming the web ui is up and running)

**Comment by gmc99** [comment]
Hi Mickael,
thanks for coming back to me. If I run socawebui.sh status it returns -
`SOCA is running with PIDs:  5426 6785 6786 6787`
but the final 3 PID's keep cycling. 
here is the gunicorn ps output -
```
root      5426     1  0 15:09 ?        00:00:00 /apps/soca/soca-00/python/3.7.1/bin/python3.7 /apps/soca/soca-00/python/latest/bin/gunicorn app:app -b 0.0.0.0:8443 --workers 3 --log-level warning --certfile cert.crt --keyfile cert.key --log-file application_output.log --daemon
root      6808  5426  0 15:36 ?        00:00:00 /apps/soca/soca-00/python/3.7.1/bin/python3.7 /apps/soca/soca-00/python/latest/bin/gunicorn app:app -b 0.0.0.0:8443 --workers 3 --log-level warning --certfile cert.crt --keyfile cert.key --log-file application_output.log --daemon
root      6809  5426  0 15:36 ?        00:00:00 /apps/soca/soca-00/python/3.7.1/bin/python3.7 /apps/soca/soca-00/python/latest/bin/gunicorn app:app -b 0.0.0.0:8443 --workers 3 --log-level warning --certfile cert.crt --keyfile cert.key --log-file application_output.log --daemon
root      6810  5426  0 15:36 ?        00:00:00 /apps/soca/soca-00/python/3.7.1/bin/python3.7 /apps/soca/soca-00/python/latest/bin/gunicorn app:app -b 0.0.0.0:8443 --workers 3 --log-level warning --certfile cert.crt --keyfile cert.key --log-file application_output.log --daemon
```
I tried a start / stop and there is no difference.
If I look in the application_output.log I see 
```
[2020-10-18 15:37:39 +0000] [5426] [CRITICAL] WORKER TIMEOUT (pid:6858)
[2020-10-18 15:38:09 +0000] [5426] [CRITICAL] WORKER TIMEOUT (pid:6872)
[2020-10-18 15:38:09 +0000] [5426] [CRITICAL] WORKER TIMEOUT (pid:6873)
[2020-10-18 15:38:09 +0000] [5426] [CRITICAL] WORKER TIMEOUT (pid:6874)
[2020-10-18 15:38:40 +0000] [5426] [CRITICAL] WORKER TIMEOUT (pid:6890)
[2020-10-18 15:38:40 +0000] [5426] [CRITICAL] WORKER TIMEOUT (pid:6891)
[2020-10-18 15:38:40 +0000] [5426] [CRITICAL] WORKER TIMEOUT (pid:6892)
```
I can't reach the web UI port 8443 either from curl or a web browser - wget does at least say it can connect -
```
# wget  https://localhost:8443
--2020-10-18 15:32:42--  https://localhost:8443/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8443... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8443... connected.
```
thanks
Gerard

**Comment by mcrozes** [comment]
Hi Gerard - 

Can you send me the application.log file as well as the output of `df -h` to  <my github username> at amazon.com ?

**Comment by ahmedelz** [comment]
/apps is a mount of EFS file system which is deployed in bursting mode. Depending on how much data you might have added to /apps, your file system might have run out of burst credits. In Amazon CloudWatch console, can you check the "Burst Credit Balance Average" and "Permitted Throughput Average" for this EFS file system? In AWS console, go to EFS file system -> click the file system corresponding to Apps -> Monitoring -> "See more in CloudWatch".

**Comment by gmc99** [comment]
Hi,
If I look at cloudwatch I see the following (I've included both the data and apps FS's for comparison-
/apps FS
BCBalanace = 0
PermTput = 1.05M
/data FS
BCBalanace = 2.31T
PermTput = 105M

If I look at the monitoring on the apps FS it says - "throughput utilization is high - negative effect on performance"
the Throughput Utilization is at 99.4% on the 12h graph. Longer timeframe graphs just show 1.6%.

So is this the problem - and how do I solve it - I'm reasonably new to AWS especially at this level of detail.

thanks

**Comment by ahmedelz** [comment]
The data provided for /apps confirms that EFS ran out of burst credit balance and that permitted throughput is too low. You'll need to change the EFS associated with /apps to use ProvisionedThroughput and provide a minimum of 5 MB/sec. In AWS console, go to EFS -> click on the file system corresponding to /apps -> Edit -> Change Throughput mode to "Provisioned", then add a value of 5 or higher (the unit is MiB/s). Then click save changes. 

Go back to the EC2 console and restart SOCA scheduler node. Give it a few minutes to reboot, then you should be able to access SOCA web ui.

**Comment by gmc99** [comment]
Hi,

wow that's fixed it thanks. That FS doesn't get much use and so it's probably been reducing it's busting until it fell over. I had noticed the machine was getting very slow in responding and as soon as I changed provision it sprung back to life. I can get back in.

thanks for your help.

**Comment by ahmedelz** [comment]
Hi @gmc99 

Thank you for confirming that the proposed solution fixed it. 

The scheduler node has cronjobs that run every minute from /apps file share to automate the cluster scale-up and scale-down operation. If the cluster isn't used frequently, I'd recommend stopping the Scheduler instance (that would save you money as well) and also enable the EFS file system to start building credits when it is not used. Another possible solution would be to reduce the frequency so that the cronjobs run every two minutes or may be every three minutes. This would have a slight increase in the time it takes to create a new node when a new job is submitted.

**Comment by gmc99** [comment]
Hi @ahmedelz 
I'll look at that
thanks
