### ISSUE TITLE
Machines failing to run

### ISSUE THREAD

**Issue by gmc99** [awslabs/scale-out-computing-on-aws#40]
Hi,
I have a soca (2.0.1) system that's been running OK for 6 months. In the last couple of days when you launch a job  - from the soca GUI - the job launches but the machine never completes and just sits in the queue.

The machine starts but doesn't run through the normal soca startup build - (running cluster_node_bootstrap/*) Also there is no log file for the machine in that directory.
The queue log - desktop.log - looks OK - it finds the job, queues it then waits for it to come back - eventually after an hour kills and restarts it. Other logs don't show any errors or warnings

thanks
Gerard

**Comment by jsynack** [comment]
Hello @gmc99,

Sorry to hear about the problems you are having.

If this is in the past couple of days it may be related to some recent Python/PIP changes.

Can you try forcing an older version of `pip` in your `UserData` section that is generated? 

https://github.com/awslabs/scale-out-computing-on-aws/blob/abd47d2b49eb5c6999d7f433b6a5a7d69c4d29d7/source/soca/cluster_manager/cloudformation_builder.py#L65-L75

Quick-fix to adjust to force pip 20.3.3 (do not include the >>>> part - it is just point out the critical line):

```
EASY_INSTALL=$(which easy_install-2.7)
$EASY_INSTALL pip==20.3.3 >>>> Enforce this PIP version
PIP=$(which pip2.7)
$PIP install awscli
```

This may solve your problem and restore functionality.

**Comment by gmc99** [comment]
Hi,
that's great that's fixed it - thanks very much 👍

**Comment by jsynack** [comment]
Greetings @gmc99,

Glad to hear that it has fixed your issue.

( fix courtesy of @mcrozes )

**Comment by ahmedelz** [comment]
Hello @gmc99, 
Just to add more color on the issue here is that SOCA 2.5 and all prior releases were based on Python2.7. PIP no longer supports Python2.7 with their new releases so the workaround above restricts PIP to that latest version that works on Python2.7. SOCA 2.6.0 and 2.6.1 migrated to python3 so newer versions will not run into the issue here.

**Comment by gmc99** [comment]
Hi,

This has worked for the last 3 months but is probably an further issue with pip again - instances start but fail during startup - they don't become accessible SOCA instances - they last and hour and then terminate.

Here is an extract from the messages file of a clients that has tried to start -
thanks again

```
May  6 19:25:45 ip-10-0-109-95 cloud-init: Cloud-init v. 19.4 running 'modules:final' at Thu, 06 May 2021 19:25:45 +0000. Up 30.01 seconds.
May  6 19:25:45 ip-10-0-109-95 cloud-init: + export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/bin
May  6 19:25:45 ip-10-0-109-95 cloud-init: + PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/bin
May  6 19:25:45 ip-10-0-109-95 cloud-init: + [[ centos7 == \c\e\n\t\o\s\7 ]]
May  6 19:25:45 ip-10-0-109-95 cloud-init: ++ which easy_install-2.7
May  6 19:25:45 ip-10-0-109-95 cloud-init: + EASY_INSTALL=/usr/bin/easy_install-2.7
May  6 19:25:45 ip-10-0-109-95 cloud-init: + /usr/bin/easy_install-2.7 pip==20.3.3
May  6 19:25:45 ip-10-0-109-95 dracut: dracut-033-572.el7
May  6 19:25:45 ip-10-0-109-95 dracut: Executing: /usr/sbin/dracut --quiet --hostonly --hostonly-cmdline --hostonly-i18n --hostonly-mode strict -o "plymouth dash resume ifcfg" --mount "/dev/disk/by-uuid/f41e390f-835b-4223-a9bb-9b45984ddf8d /sysroot xfs defaults" --no-hostonly-default-device -f /boot/initramfs-3.10.0-1160.25.1.el7.x86_64kdump.img 3.10.0-1160.25.1.el7.x86_64
May  6 19:25:45 ip-10-0-109-95 cloud-init: Searching for pip==20.3.3
May  6 19:25:45 ip-10-0-109-95 cloud-init: Reading https://pypi.python.org/simple/pip/
May  6 19:25:45 ip-10-0-109-95 cloud-init: Couldn't find index page for 'pip' (maybe misspelled?)
May  6 19:25:45 ip-10-0-109-95 cloud-init: Scanning index of all packages (this may take a while)
May  6 19:25:45 ip-10-0-109-95 cloud-init: Reading https://pypi.python.org/simple/
May  6 19:25:45 ip-10-0-109-95 cloud-init: No local packages or download links found for pip==20.3.3
May  6 19:25:45 ip-10-0-109-95 cloud-init: error: Could not find suitable distribution for Requirement.parse('pip==20.3.3')
May  6 19:25:45 ip-10-0-109-95 cloud-init: 2021-05-06 19:25:45,459 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
May  6 19:25:45 ip-10-0-109-95 cloud-init: 2021-05-06 19:25:45,462 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
May  6 19:25:45 ip-10-0-109-95 cloud-init: 2021-05-06 19:25:45,462 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
May  6 19:25:45 ip-10-0-109-95 ec2:
```

**Comment by mcrozes** [comment]
I have an older SOCA cluster with the fix provided above ``` pip==20.3.3```, I migrated it to use the system python and it's been working perfectly for the last couple of months:

My recommendation is to edit this section https://github.com/awslabs/scale-out-computing-on-aws/blob/main/source/soca/cluster_manager/cloudformation_builder.py#L70-L77  and force utilisation of Py3 (we migrated to Py3 since SOCA 2.5.0 as Py2 is now EOL)

```
yum install -y python3
pip3 install awscli
yum install -y nfs-utils # enforce install of nfs-utils
```

Here is what my file looks like (I am using CentOS as base image)

```
if [[ "''' + params['BaseOS'] + '''" == "centos7" ]] || [[ "''' + params['BaseOS'] + '''" == "rhel7" ]];
    then
        yum install -y python3
        pip3 install awscli
        yum install -y nfs-utils # enforce install of nfs-utils
else
.......
```

**Comment by gmc99** [comment]
Hi
we've started some instances out of soca to keep us going until we get some data shipped out, but I should be able to try it in the next week
thanks for the speedy response
cheers

**Comment by mcrozes** [comment]
Hey @gmc99  -

Following-up on this thread. Let us know if your cluster is back online.

**Comment by gmc99** [comment]
Hi,

it's all working - been a busy week 
thanks again
