### ISSUE TITLE
Looking for a way to connect NiceDcv to compute node

### ISSUE THREAD

**Issue by sysdori** [awslabs/scale-out-computing-on-aws#41]
Hi, 
I am testing ANSYS Fluent(2020R1) on SOCA2.6. And the CLI submit job test is complete, I am looking for a way to run and monitor the job in Fluent Desktop by connecting to compute nodes with NiceDcv.
 
Is there a way to NiceDCV connect to compute node after to launch nodes(SPOT)?
If you have to know the way, please let me know.  It will be very useful if this is possible.

Compute node is being used by creating CentOS7 AMI.
I am using the same AMI on my Linux Desktop.

Thanks,
SG

**Comment by mcrozes** [comment]
Hello @sysdori -

For this use case I'd go with launching a DCV session via the usual way (https://awslabs.github.io/scale-out-computing-on-aws/web-interface/create-virtual-desktops/). Then, redirect the Fluent log to your EFS home (/data/home) directory. By doing that you will be able to access the fluent log in real-time from your DCV even though you are actually not on the compute node

example:
```
#!/bin/bash
#PBS -N testfluent
#PBS -V -j oe -o  ol.qlog
#PBS -P test
#PBS -q ansys

cd /data/home/mcrozes

# Export relevant path
export ANSYSLMD_LICENSE_FILE=21055@xxxxxxx
export PATH=$PATH:/apps/ansys_inc/v195/fluent/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/apps/ansys_inc/v195/fluent/lib:/apps/ansys_inc/v195/fluent/lib/lnamd64

# Run Fluent job
echo "Simulation Start: " `date`
/apps/ansys_inc/v195/fluent/bin/fluent 3ddp -ssh -g -i /data/home/mcrozes/journal.log -t36 >> /data/home/mcrozes/simulation_fluent.log 2>&1
echo "Simulation End:" `date`
```

Once the job is running, launch Ansys and open `/data/home/mcrozes/simulation_fluent.log`.

**Comment by sysdori** [comment]
Hi, mcrozes.

Thank you so much for your answer.

I modified the run script, and then I checked simulation_fluent.log
===
socaadmin@ip-172-20-2-197 guitest]$ tail -f simulation_fluent.log 
  iter  continuity  x-velocity  y-velocity  z-velocity      energy  do-intensi     time/iter
   873  3.7992e-05  3.9431e-07  8.7345e-07  8.6915e-07  6.0673e-10  5.2824e-08  0:07:20  127
   874  3.6802e-05  3.7590e-07  8.5213e-07  8.4292e-07  6.0780e-10  5.2824e-08  0:06:05  126
   875  3.6447e-05  3.6064e-07  8.3015e-07  8.2531e-07  6.0768e-10  5.2824e-08  0:05:05  125
   876  3.7151e-05  3.6941e-07  8.3454e-07  8.2905e-07  6.0734e-10  5.2483e-08  0:07:10  124
===

And launched Ansys fluent GUI , then I tried to open the log file, 
Which menu should I use to read the log normally?

Sorry, I do not have deep knowledge about ANSYS fluent tools.

Thanks,
Dori.

**Comment by sysdori** [comment]
Dear mcrozes.
Thanks for your answer on this,
I checked that the log is displayed normally by referring to the script you gave me, but I am looking for how to read(or import) the log in Fluent Desktop.
I'll do some performance tests and find out how to check the real-time log in the GUI.

Thanks,
SalGu.

**Comment by mcrozes** [comment]
Hey @sysdori  -

I'd recommend to check with your local Ansys support as we are maintainer of SOCA AWS platform and do not have any expertise with any engineering application.
