### ISSUE TITLE
Lambda Botocore Deprecation

### ISSUE THREAD

**Issue by gmc99** [awslabs/scale-out-computing-on-aws#42]
Hi,

I received an email from AWS about my CloudFormation stacks  and 'Lambda Botocore Deprecation' is this something I need to worry about ahead of it's removal in April? - I am running SOCA 2.0.1

If so and I need to upgrade to the latest soca 2.6.1 release is there an easy way to migrate the system over?

thanks
Gerard

**Comment by ahmedelz** [comment]
Hello Gerard, 

There are 2 Lambda functions that SOCA uses which depend on `cfnresponse.py`. If you're running SOCA 2.0.1, most likely you have the older version of cfnresponse.py. You can confirm by checking the first line of code of `cfnresponse.py` in `soca-${StackName}-Metrics` and `soca-${StackName}-PreRequisitesCheck`. 

If the first line of code below the comment section is:
`from botocore.vendored import requests`

Then this is the old version and it needs to be updated. To update the code, you would need to copy the updated Python code at the bottom of this [link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html) and replace the old content in `cfnresponse.py` then click on "`Deploy`" to update the Lambda function. Don't forget there are two functions that you need to check and update.

**Comment by gmc99** [comment]
Hi,
I needed to wait for a time to get onto the system. I've updated both functions and everything seems to be running fine

thanks for your help
