### ISSUE TITLE
Scaling issue with virtual desktops on 4K screens.

### ISSUE THREAD

**Issue by fabriceschlegel** [awslabs/scale-out-computing-on-aws#50]
Current state:
When using the Linux virtual desktops from a Windows laptop, independently of the Linux OS, virtual session are only rendered properly when connecting directly from a web browser. When using the DCV client, the auto scaling won't work on a 4K screen, leading to a very small font size. Thanks for looking into it!

**Comment by walple** [comment]
Hi Fabrice, I checked the DCV Forum (https://forums.aws.amazon.com/forum.jspa?forumID=366) and was not able to find matching thread. The DCV support team should be best suited to determine what the issue may be, they can be reached via helpdesk@nice-software.com .

**Comment by mcrozes** [comment]
Closing ticket. Let us know if contacting NICE Helpdesk solved your issue.
