### ISSUE TITLE
bug and bug fix: automatic hibernation  (Linux desktops)

### ISSUE THREAD

**Issue by tammy-ruby-cherry** [awslabs/scale-out-computing-on-aws#55]
**RELEVANT TO**  
Automatically hibernating desktops that were launched but never accessed  
Probably also relevant to auto-stopping, but that's not relevant to me

**LOCATION**  
File:  /web_cluster_ui/scheduled_tasks/manage_dcv_instances_lifecycle.py   
Function: linux_auto_stop_instances (line 238)
Location in function:  if..else loop starting  (line 297):     
```
if "last-disconnection-time" not in session_info["DCV"].keys():
    # handle case where user launched DCV but never accessed it
    last_dcv_disconnect = parse(session_info["DCV"]["creation-time"])
else:
    last_dcv_disconnect = parse(session_info["DCV"]["last-disconnection-time"])
```

**WHAT'S GOING WRONG:**   
"last-disconnection" time is *always* a session_info["DCV"] key (see the relevant boto3 command), thus the condition is always false, and the conditional branches to the else statement.  If the user has never connected to the instance, then the value of the "last-connection-time" key is "", "parse" is trying to parse an empty string and the script crashes. 

**BUG FIX**  
Replace line 297 with:   
`if  session_info["DCV"]["last-disconnection-time"]] == "": `

**Comment by mcrozes** [comment]
I was able to reproduce this issue and confirmed your fix address this issue. We will include it in our next release.
