### ISSUE TITLE
How to enable MetricBeat when starting 'alwayson queue' ?

### ISSUE THREAD

**Issue by sysdori** [awslabs/scale-out-computing-on-aws#57]
Dear, SOCA Engineer.
I have configured an environment where customers can use optical simulation on SOCA.
I used Alwayson Queue as a usage environment, and analysis work is normally executed.

I ran Always on with the script below, but the "MetricBeat" setting option was not found.
"/apps/soca/$SOCA_CONFIGURATION/cluster_manager/add_nodes.py "

---------------------------------------------------------------------------------
#python3 /apps/soca/$SOCA_CONFIGURATION/cluster_manager/add_nodes.py   --desired_capacity { }  --instance_type { }  --job_name always_on_capacity --instance_ami { }  --job_owner hpcadmin --root_size 10 --spot_price auto --queue alwayson  --keep_forever true

#pbsnodes -a
     resources_available.arch = linux
     resources_available.asg_spotfleet_id = sfr-fd4be2c0-86bd-4462-9b68-aac34ad31272
     resources_available.availability_zone = ap-northeast-2b
     resources_available.compute_node = job2e0a6c5f-a75a-4c15-a36d-263b9f4eb230
     resources_available.host = ip-172-20-2-173
     resources_available.instance_id = i-0c7ad8e920cb89709
     resources_available.instance_type = c5.24xlarge
     resources_available.mem = 193526880kb
     resources_available.ncpus = 48
     resources_available.subnet_id = subnet-01c6b2a71bfa812cb
     resources_available.vnode = ip-172-20-2-173
     resources_assigned.accelerator_memory = 0kb
     resources_assigned.hbmem = 0kb
     resources_assigned.mem = 0kb
     resources_assigned.naccelerators = 0
     resources_assigned.ncpus = 0
     resources_assigned.vmem = 0kb
---------------------------------------------------------------------------------
And I configed that "PBS -l system_metrics = true" in the script and then I checked that metrics is true when qstat -xf option.

[hpcadmin@ip-172-20-2-14 cluster_manager]$ qstat -xf 1089
Job Id: 1089.ip-172-20-2-14
    Job_Name = testa4_Queue_test
    Job_Owner = testadmin@ip-172-20-2-14.ap-northeast-2.compute.internal
    resources_used.cpupercent = 3901
    resources_used.cput = 06:26:17
    resources_used.mem = 15402808kb
    resources_used.ncpus = 192
    resources_used.vmem = 22877768kb
    resources_used.walltime = 00:08:22
    job_state = F
    queue = alwayson
    server = ip-172-20-2-14
    Checkpoint = u
    ctime = Fri Aug 27 08:46:01 2021
    Error_Path = ip-172-20-2-14.ap-northeast-2.compute.internal:/data/home/test
        admin/myjob/testadmin_testd/Logs/error_run_testa4_Queue_test.err
    exec_host = ip-172-20-2-139/0*48+ip-172-20-2-152/0*48+ip-172-20-2-175/0*48+
        ip-172-20-2-173/0*48
    exec_vnode = (ip-172-20-2-139:ncpus=48)+(ip-172-20-2-152:ncpus=48)+(ip-172-
        20-2-175:ncpus=48)+(ip-172-20-2-173:ncpus=48)
    Hold_Types = n
    Join_Path = n
    Keep_Files = n
    Mail_Points = a
    mtime = Fri Aug 27 09:00:08 2021
    Output_Path = ip-172-20-2-14.ap-northeast-2.compute.internal:/data/home/tes
        tadmin/myjob/testadmin_testd/Logs/output_run_testa4_Queue_test.out
    Priority = 0
    qtime = Fri Aug 27 08:46:01 2021
    Rerunable = True
    Resource_List.mpiprocs = 4
    Resource_List.ncpus = 192
    Resource_List.nodect = 4
    Resource_List.place = free
    Resource_List.select = 4:ncpus=48:mpiprocs=1
    **Resource_List.system_metrics = True**
    Resource_List.walltime = 24:00:00
    stime = Fri Aug 27 08:51:46 2021
    session_id = 8393
    jobdir = /data/home/testadmin
    substate = 92
======================================================================
Is there a way to enable metrics when creating an Alwayson Queue?

Can you please check if the method I used the PBS -l option is correct?

Best Regards,
JungIn

**Comment by mcrozes** [comment]
Hello @sysdori  -

MetricBeat support for AlwaysOn is not something we are supporting today, however you can edit `add_nodes.py` and add support for it.

To do that, add a new `parser.add_argument()`  named `system_metrics` directly after the list of existing arguments (https://github.com/awslabs/scale-out-computing-on-aws/blob/main/source/soca/cluster_manager/add_nodes.py#L842)

```python
parser.add_argument('--system_metrics', default=True, help='Add/Remove support for MetricBeat')
```

Then submit a new capacity via `add_nodes.py` and specify `--system_metrics` parameter:

```
python3 /apps/soca/$SOCA_CONFIGURATION/cluster_manager/add_nodes.py --desired_capacity { } \
 --instance_type { } --job_name always_on_capacity --instance_ami { } \
 --job_owner hpcadmin --root_size 10 --spot_price auto --queue alwayson --keep_forever true \
 --system_metrics true # <--- Add this
```

Alternatively, if you want to force MetricBeat for all compute nodes, you can edit the `if` statement https://github.com/awslabs/scale-out-computing-on-aws/blob/main/source/soca/cluster_node_bootstrap/ComputeNodeConfigureMetrics.sh#L15 and force this loop to be executed for all jobs `if "true" == "true"; then ...`

**Comment by sysdori** [comment]
Dear, mcrozes.

Thank you for your support.
I applied the script in the first way, and I think I will be able to test it tomorrow.

Thanks,
Sysdori.

**Comment by sysdori** [comment]
Dear, mcrozes.
I modified the source code by referring to your guide and confirmed that system_metrics are automatically applied in the Always on compute node.
Thanks,
sysdori
