### ISSUE TITLE
[Request] Elastic Search job generation

### ISSUE THREAD

**Issue by sysdori** [awslabs/scale-out-computing-on-aws#58]
Hi, SOCA engineer.

I found an issue where job results were not sent to elasticsearch when using alwayson queue.

I am attaching two of the job logs. One is the part tested by running the SPOT instance using normal queue, and the other is the log executed by creating a c5a.24xlarge 4-node Alwayson Queue Cluster. 

###normal queue : Successful log transmission to elastic search

09/01/2021 11:00:07;a;1147.ip-172-20-2-14;Resource_List.base_os=centos7 Resource_List.instance_ami=ami-0e6053f2809d551d0 Resource_List.instance_type=t3.micro Resource_List.nodes=1 Resource_List.spot_price=auto Resource_List.ht_support=false Resource_List.root_size=10
09/01/2021 11:00:09;a;1147.ip-172-20-2-14;Resource_List.select=1:ncpus=1:compute_node=job1147
09/01/2021 11:00:09;a;1147.ip-172-20-2-14;Resource_List.stack_id=soca-hpc2-job-1147
09/01/2021 11:00:09;a;1147.ip-172-20-2-14;Resource_List.error_message=UNSET
09/01/2021 11:10:32;S;1147.ip-172-20-2-14;user=hpcadmin group=hpcadmin project=mpirun jobname=mpitest queue=normal ctime=1630461602 qtime=1630461602 etime=1630461602 start=1630462232 exec_host=ip-172-20-2-80/0 exec_vnode=(ip-172-20-2-80:ncpus=1) Resource_List.base_os=centos7 Resource_List.ht_support=false Resource_List.instance_ami=ami-{id} Resource_List.instance_type=t3.micro Resource_List.ncpus=1 Resource_List.nodect=1 Resource_List.nodes=1 Resource_List.place=scatter Resource_List.root_size=10 Resource_List.select=1:ncpus=1:compute_node=job1147 Resource_List.spot_price=auto Resource_List.stack_id=soca-hpc2-job-1147 resource_assigned.ncpus=1
09/01/2021 11:10:39;E;1147.ip-172-20-2-14;user=hpcadmin group=hpcadmin project=mpirun jobname=mpitest queue=normal ctime=1630461602 qtime=1630461602 etime=1630461602 start=1630462232 exec_host=ip-172-20-2-80/0 exec_vnode=(ip-172-20-2-80:ncpus=1) Resource_List.base_os=centos7 Resource_List.ht_support=false Resource_List.instance_ami=ami-{id} Resource_List.instance_type=t3.micro Resource_List.ncpus=1 Resource_List.nodect=1 Resource_List.nodes=1 Resource_List.place=scatter Resource_List.root_size=10 Resource_List.select=1:ncpus=1:compute_node=job1147 Resource_List.spot_price=auto Resource_List.stack_id=soca-hpc2-job-1147 session=1484 end=1630462239 Exit_status=0 resources_used.cpupercent=66 resources_used.cput=00:00:04 resources_used.mem=0kb resources_used.ncpus=1 resources_used.vmem=0kb resources_used.walltime=00:00:06 run_count=1
09/01/2021 12:00:00;L;license;floating license hour:0 day:0 month:0 max:0

###mpi normal queue test script
#PBS -N mpitest
#PBS -V -j oe -o output.qlog
#PBS -P mpirun
#PBS -q normal
#PBS -l instance_ami=ami-{useramiid] -l instance_type=t3.micro -l spot_price=auto -l nodes=1 -l base_os=centos7
mpirun --hostfile hostfile -np 2 ./mpi_hello_world

###alwayson queue : Logs are not sent to elastic search
08/31/2021 08:00:00;L;license;floating license hour:0 day:0 month:0 max:0
08/31/2021 08:07:02;Q;1130.ip-172-20-2-14;user=design2 group=design2 project=_pbs_project_default jobname=SIGNAL02_KSO queue=alwayson ctime=1630364822 qtime=1630364822 etime=1630364822 Resource_List.mpiprocs=4 Resource_List.ncpus=192 Resource_List.nodect=4 Resource_List.place=free Resource_List.select=4:ncpus=48:mpiprocs=1 Resource_List.system_metrics=True Resource_List.walltime=240:00:00
08/31/2021 08:28:33;S;1130.ip-172-20-2-14;user=design2 group=design2 project=_pbs_project_default jobname=SIGNAL02_KSO queue=alwayson ctime=1630364822 qtime=1630364822 etime=1630364822 start=1630366113 exec_host=ip-172-20-2-174/0*48+ip-172-20-2-110/0*48+ip-172-20-2-169/0*48+ip-172-20-2-147/0*48 exec_vnode=(ip-172-20-2-174:ncpus=48)+(ip-172-20-2-110:ncpus=48)+(ip-172-20-2-169:ncpus=48)+(ip-172-20-2-147:ncpus=48) Resource_List.mpiprocs=4 Resource_List.ncpus=192 Resource_List.nodect=4 Resource_List.place=free Resource_List.select=4:ncpus=48:mpiprocs=1 Resource_List.system_metrics=True Resource_List.walltime=240:00:00 resource_assigned.ncpus=192
08/31/2021 08:29:42;E;1130.ip-172-20-2-14;user=design2 group=design2 project=_pbs_project_default jobname=SIGNAL02_KSO queue=alwayson ctime=1630364822 qtime=1630364822 etime=1630364822 start=1630366113 exec_host=ip-172-20-2-174/0*48+ip-172-20-2-110/0*48+ip-172-20-2-169/0*48+ip-172-20-2-147/0*48 exec_vnode=(ip-172-20-2-174:ncpus=48)+(ip-172-20-2-110:ncpus=48)+(ip-172-20-2-169:ncpus=48)+(ip-172-20-2-147:ncpus=48) Resource_List.mpiprocs=4 Resource_List.ncpus=192 Resource_List.nodect=4 Resource_List.place=free Resource_List.select=4:ncpus=48:mpiprocs=1 Resource_List.system_metrics=True Resource_List.walltime=240:00:00 session=8560 end=1630366182 Exit_status=0 resources_used.cpupercent=0 resources_used.cput=00:00:00 resources_used.mem=696kb resources_used.ncpus=192 resources_used.vmem=12904kb resources_used.walltime=00:00:05 run_count=1

###alwayson queue addnode command
python3 /apps/soca/$SOCA_CONFIGURATION/cluster_manager/add_nodes.py  --desired_capacity 4 --instance_type c5a.24xlarge --job_name always_on_capacity --instance_ami ami{id}  --job_owner hpcadmin --root_size 10 --spot_price auto --queue alwayson  --keep_forever true --spot_allocation_strategy capacity-optimized --system_metrics true

###alwayson queue run script
#PBS -N desig12_post2
#PBS -l walltime=00:14400:00
#PBS -q alwayson
#PBS -o "/data/home/design2/myjob/queue6/Logs/output_run_desig12_post2.out"
#PBS -e "/data/home/design2/myjob/queue6/Logs/error_run_desig12_post2.err"
#PBS -l select=4:ncpus=48:mpiprocs=1
#PBS -l system_metrics=True
#PBS -p 100
export LD_LIBRARY_PATH= {  }
export PATH={  }
mpirun -ppn 1 "/apps/{  application path }" -sv5 "/data/home/design2/myjob/{ input date path }" {user option} -mpi IntelMPI
qstat -xf $PBS_JOBID | sed '1,2d' >> ~/logs/job_detail.log
qstat -x $PBS_JOBID | sed '1,2d' >> ~/logs/job.log

Is there any way to fix this problem by modifying the script in the qsub {script} command?

Thanks,
Sysdori.

**Comment by mcrozes** [comment]
Hey @sysdori -

Can you check ` /apps/soca/<YOUR_CLUSTER>/cluster_analytics/job_tracking.log` for ElasticSearch ingestion log and see if you have any reference to your job ID: 1130

Also, you can try to launch the ingestion manually via 
```
source /etc/environment; /apps/soca/<YOUR_CLUSTER>/python/latest/bin/python3 /apps/soca/<YOUR_CLUSTER>/cluster_analytics/job_tracking.py
```

By default, this script ingest jobs that completed within 24 hours. You may need to edit line 156:
```
days_to_check = 1 # change this value as needed
```

**Comment by sysdori** [comment]
Dear mcrozes.


Thanks for your kind explanation.
I was able to fix the error by doing log analysis and modifying the PBS script.

Best Regards,
Sysdori.
