### ISSUE TITLE
c5d.18xlarge doesn't come online

### ISSUE THREAD

**Issue by bsmith94** [awslabs/scale-out-computing-on-aws#6]
I launched a c5d.18xlarge compute node via SOCA and never saw it come online. This was repeated multiple times. c5.18xlarge works fine, so it may be a conflict with the instance storage.

My ami is an unmodified clone of ali2, created 12-Feb-2020.

```
$ python3 ./add_nodes.py --instance_type c5d.18xlarge --desired_capacity 1 --queue alwayson --keep_forever --instance_ami ami-0cd51c4f054a95d10 --job_name always_on_capacity --job_owner bsmith --base_os amazonlinux2
```

After allowing 15 minutes for the node to come up, ```pbsnodes -l``` listed the node as down, communication failure.

**Comment by mcrozes** [comment]
Hey Brian -
Closing this as this request have been merged on the new version. As usual, thanks again for your contributions
