### ISSUE TITLE
minor logging bug in manage_dcv_instances_lifecycle.py 

### ISSUE THREAD

**Issue by tammy-ruby-cherry** [awslabs/scale-out-computing-on-aws#67]
Because it's all about the logs, right?

**Describe the bug**
Line 352: ` .format(instance_ID)` is missing from the end of the logger.info statement

- Currently:   `logger.info("linux_auto_stop_instance: {} currently has active DCV sessions")`
- Should be:  
 `logger.info("linux_auto_stop_instance: {} currently has active DCV sessions").format(instance_ID))`

**To Reproduce**
N/A

**Expected behavior**
N/A

**Please complete the following information about the solution:**
- [ ] Version: 2.7.

**Comment by mcrozes** [comment]
Hey @tammy-ruby-cherry  -

Correct, we are missing `instance_id` here. Will test it, see if we are missing it anywhere else and push a fix to Github soon.

`logger.info("linux_auto_stop_instance: {} currently has active DCV sessions".format(instance_id))`

Thanks for your bug report!

**Comment by mcrozes** [comment]
Closed as discussed via email.
