### ISSUE TITLE
Add ADConnector compatibility

### ISSUE THREAD

**Issue by francozulian** [awslabs/scale-out-computing-on-aws#70]
We tried using SOCA and connecting it to an ADConnector type directory, but we needed to change find_existing_resources.py code in order for it to work. This was caused because of the attribute difference between the directory types (VpcSettings | ConnectSettings)

Also, not sure if related to the ADConnector per se, but we had an issue when getting the directory dns on install_soca.py, as it seems to get a string with a space inbetween ([ip, ip]), what causes it to break trying to only use the first part ("[ip,")

The workaround we used (it may not be the most appropriate), was checking the directory type before looking for it's attributes, and wrapping the dns data on a str() function

<img width="803" alt="image" src="https://user-images.githubusercontent.com/52921350/157256524-b59aa3d7-6941-445f-9b2b-a01bea8fbe12.png">
<img width="592" alt="image" src="https://user-images.githubusercontent.com/52921350/157256662-90b713ed-47bd-4e2d-a6eb-f6abc7b8b162.png">

I'll look forwart to hear your comments

Thanks in advance

**Comment by mcrozes** [comment]
Hey @francozulian - Sorry for the super late reply. We are about to refresh SOCA with a new version soon. I would recommend to try with the updated codebase and see if this issue still persists
