### ISSUE TITLE
when accessing soca swagger api, it shows Not Authorized

### ISSUE THREAD

**Issue by aqiao** [awslabs/scale-out-computing-on-aws#75]
Hi team,
As title, i have a sudo user _admin_, and when i access soca swagger api:_/api/ldap/user_, it shows "Not Authorized". Actually other apis also show the same error. I checked the code and found there is decorator method named admin_api applied on these methods
```
def admin_api(f):
    @wraps(f)
    def admin_resource(*args, **kwargs):
        user = request.headers.get("X-SOCA-USER", None)
        token = request.headers.get("X-SOCA-TOKEN", None)
        if token == config.Config.API_ROOT_KEY:
                return f(*args, **kwargs)

        if user is None or token is None:
            return {"success": False, "message": "Not Authorized"}, 401
        else:
            token_has_sudo = ApiKeys.query.filter_by(token=token,
                                                     user=user,
                                                     scope="sudo",
                                                     is_active=True).first()
            if token_has_sudo:
                return f(*args, **kwargs)
            else:
                return {"success": False, "message": "Not authorized"}, 401
    return admin_resource
```
As code shown, it needs header parameters: X-SOCA-USER and X-SOCA-TOKEN, however even i provided these ones, it also show the same error
<img width="731" alt="WechatIMG364" src="https://user-images.githubusercontent.com/5533748/180121270-2eb1414b-36c8-45a9-b825-ba5503e37d5b.png">
<img width="462" alt="WechatIMG365" src="https://user-images.githubusercontent.com/5533748/180121279-37088d22-9200-40ac-8814-131b53bccd90.png">

Please could you guide me how to fix it?

**Comment by mcrozes** [comment]
Hello @aqiao  - Just to confirm you are using the API Token (https://awslabs.github.io/scale-out-computing-on-aws/web-interface/control-hpc-job-with-http-web-rest-api/#step1-retrieve-your-api-key) and not the user password for `X-SOCA-TOKEN`

**Comment by aqiao** [comment]
hi @mcrozes ,
Thanks for your response, it works. However, when i call` /api/user/api_key`, it still show "Not Authorized", then i checked the code again, i found the `get` method is marked as @restricted_api, then i checked the restricted_api code as below

```
def restricted_api(f):
    @wraps(f)
    def restricted_resource(*args, **kwargs):
        token = request.headers.get("X-SOCA-TOKEN", None)
        if token == config.Config.API_ROOT_KEY:
                return f(*args, **kwargs)
        return {"success": False, "message": "Not authorized"}, 401
    return restricted_resource
```
it used config.Config.API_ROOT_KEY as token, and config.Config.API_ROOT_KEY value comes from os environment variable :os.environ["SOCA_FLASK_API_ROOT_KEY"], but when i echo this variable on soca schedule node , it shows empty, so how can i get this variable

**Comment by mcrozes** [comment]
The `/api/user/api_key` is a little bit different as this endpoint returns the actual API key of the user. On older version, this endpoint was restricted to the web ui for security purpose.

On newer version, you will notice this API is now protected by `retrieve_api_key` decorator: https://github.com/awslabs/scale-out-computing-on-aws/blob/main/source/soca/cluster_web_ui/api/v1/user/api_key.py 

To access this endpoint, you will need to authenticate with X-SOCA-USER and X-SOCA-PASSWORD (aka: you regular username/password) (https://github.com/awslabs/scale-out-computing-on-aws/blob/780fcba33e72d35cf2744e100fe1951fdbf81a37/source/soca/cluster_web_ui/decorators.py#L95).

So tu summarize, to authenticate to `/api/user/api_key`, you need to use X-SOCA-USER and X-SOCA-PASSWORD (your password)
To authenticate to other APIs , you need to use X-SOCA-USER (your username) and X-SOCA-TOKEN (your API key)

If possible, I recommend upgrading your cluster to the latest version. If not possible, you can retrieve the root API key under cluster_web_ui/keys folder (https://github.com/awslabs/scale-out-computing-on-aws/blob/780fcba33e72d35cf2744e100fe1951fdbf81a37/source/soca/cluster_web_ui/socawebui.sh#L94)

**Comment by aqiao** [comment]
there is no `keys` folder under cluster_web_ui, and no `admin_api_key.txt` neither. i listed all txt files under `cluster_web_ui`

```
[root@ip-10-0-0-22 cluster_web_ui]# ls -l *.txt
-rw------- 1 root root 45 7月   8 07:31 dcv_secret_key.txt
-rw------- 1 root root 33 7月   8 07:31 flask_secret_key.txt
```

**Comment by mcrozes** [comment]
What version of SOCA are you using?

**Comment by aqiao** [comment]
2.6.4

**Comment by aqiao** [comment]
i checked socawebui.sh, it indeed created environment the variable , but every time it runs, it will generates a random string

```
            # Creating unique, random and temp credentials
            export SOCA_FLASK_FERNET_KEY=$(dd if=/dev/urandom bs=32 count=1 2>/dev/null | openssl base64)
            export SOCA_FLASK_API_ROOT_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
```

**Comment by mcrozes** [comment]
`export SOCA_FLASK_API_ROOT_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)`

You can add a print statement just after this to get the API key information when you run a socawebui.sh start or store the output of the command into a text file.
```
cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 > keys/admin_api_key.txt
chmod 600 keys/admin_api_key.txt
export SOCA_FLASK_API_ROOT_KEY=$(cat keys/admin_api_key.txt)```

**Comment by aqiao** [comment]
so i have to re-deploy soca or just re-run socawebui.sh on the existing environment?

**Comment by aqiao** [comment]
Okey, i got it. Very appreciate your support, have i nice day!!!
