### ISSUE TITLE
WindowsVDI ChangeHardward Not work - Client input malformed. os (str), session_number (str), instance_type (str) are required.

### ISSUE THREAD

**Issue by sysdori** [awslabs/scale-out-computing-on-aws#79]
**Describe the bug**
Some time ago, the ChangeHardward function did not work in Windows VDI, so I tried to reproduce it by installing SOCA in a new VPC. Similarly, this function does not work.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
1. Create WindowsVDI t3.small instance and STOP
2. Try changing to t3.medium in the ChangeHardware menu
3. The instance type does not change, and a red text message is displayed.
4. When calling desktops with API GET, the same message is displayed.
[ @cluster_manager]# curl -k -X GET  -H "X-SOCA-TOKEN: MyAPIKey"    -H "X-SOCA-USER: MysocaID"    https://soca-1201hpc-viewer-number.ap-northeast-2.elb.amazonaws.com/api/dcv/desktops
{"success": false, "message": "Client input malformed. os (str), is_active (str)  are required."}

**Please complete the following information about the solution:**
SOCA_BASE_OS="centos7"
AWS_DEFAULT_REGION="ap-northeast-2"
SOCA_VERSION="2.7.2"
SOCA_INSTALL_AMI="ami-0e4214f08b51e23cc"

[uwsig.log when action "change hardware" ]
[pid: 9569|app: 0|req: 226/347] 10.1.2.11 () {32 vars in 401 bytes} [Thu Dec  1 03:36:37 2022] GET /ping => generated 5 bytes in 116 msecs (HTTP/1.1 200) 3 headers in 193 bytes (1 switches on core 0)
/apps/soca/soca-1201hpc/python/3.7.9/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings InsecureRequestWarning,
[pid: 9569|app: 0|req: 228/348] 127.0.0.1 () {42 vars in 618 bytes} [Thu Dec  1 03:36:38 2022] PUT /api/dcv/desktop/None/modify => generated 124 bytes in 145 msecs (HTTP/1.1 400) 3 headers in 196 bytes (1 switches on core 0)
[pid: 9569|app: 0|req: 228/349] 10.1.2.11 () {70 vars in 1596 bytes} [Thu Dec  1 03:36:38 2022] POST /remote_desktop_windows/modify => generated 253 bytes in 331 msecs (HTTP/1.1 302) 4 headers in 304 bytes (1 switches on core 1)
/apps/soca/soca-1201hpc/python/3.7.9/lib/python3.7/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
[pid: 9563|app: 0|req: 21/350] 127.0.0.1 () {38 vars in 606 bytes} [Thu Dec  1 03:36:38 2022] GET /api/dcv/desktops?user=hpcadmin&os=windows&is_active=true => generated 1552 bytes in 537 msecs (HTTP/1.1 200) 3 headers in 188 bytes (1 switches on core 1)
[pid: 9569|app: 0|req: 229/351] 10.1.2.11 () {64 vars in 1425 bytes} [Thu Dec  1 03:36:38 2022] GET /remote_desktop_windows => generated 331133 bytes in 750 msecs (HTTP/1.1 200) 3 headers in 198 bytes (1 switches on core 0)

[sqlite windows_dcv_sessions]
1|socaadmin|8ade3091-6df9-4212-84be-e29c7d5.....7a|modifytest|1|stopped|ip-10-1-2-187|10.1.2.187|i-04144b2fe90b3d3cf|t3.small|3PICz8br9|bfd8201c-12ec-4f2c-a88a-f6196........|console||0|Z0FBQUFBQmppQjBNQTRpZlNmaHBTM1JsczA2NTZCT18taVJjenNaT1VuSUF2bmV1RUlQR2h4QUx0Qkh2QnNVWXNxMGhyNjJZRFFCZENReG1TUE9QZHhYeGszUjlNZVRUVXlaTE9qU0dEWVBoMWROcEloYVN4NV9aZXVocmJvSUJNZlFnLV81REF2eDR.......................................|1|2022-12-01 03:17:31.197112||0|1440|0|1440|0|1440|0|1440|0|1440|0|0|0|0

- [ ] Region: [ap-northeast-2]
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? 
- [ ] Have you checked your [service quotas] yes
- [ ] Were there any errors in the CloudWatch Logs?I can't find that log in the cloudwatch log group.

**Screenshots**
![image](https://user-images.githubusercontent.com/68527184/204960431-baaf102e-e2de-41e1-af8c-c7ef8398e98b.png)
![image](https://user-images.githubusercontent.com/68527184/204960484-376e0729-05f3-43b1-b7b2-b2e86e4dc267.png)

**Additional context**
I also installed and tested SOCA2.7.2 on another test account, but the symptoms were the same.
LinuxVDI's ChangeHardware feature is OK.

**Comment by mcrozes** [comment]
Hello  @sysdori -

We have been able to reproduce this issue and will provide a fix in the upcoming version.

Thanks for your detailed report.
