### ISSUE TITLE
Service quota check for the T instance family fails due to addition of the new Trn family

### ISSUE THREAD

**Issue by nfahlgren** [awslabs/scale-out-computing-on-aws#80]
**Describe the bug**
When requesting any T type instance, the function `verify_vcpus_limit` function in the `add_nodes.py` module can match the service quota `Quota Running On-Demand Trn instances` instead of the correct quota `Quota Running On-Demand Standard (A, C, D, H, I, M, R, T, Z) instances`. 

```
{'message': 'Job cannot start due to AWS Service limit. Max Vcpus allowed 0.0. Detected running Vcpus 0. Requested Vcpus for this job 4. Quota Name Running On-Demand Trn instances', 'quota_info': {'t3.micro': {'max_vcpus_allowed': 0.0, 'vcpus_provisioned': 4, 'quota_name': 'Running On-Demand Trn instances'}}}
```

**To Reproduce**
Request any `instance_type` in the T family with more resources than your service quota limit for Trn instances and the dry-run check will fail. 

**Expected behavior**
T family instance requests should match the `Standard (A, C, D, H, I, M, R, T, Z) instances` service quotas.

**Please complete the following information about the solution:**
- [ ] Version: v2.7.0
- [ ] Region: us-east-2
- [ ] Was the solution modified from the version published on this repository? - No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?  - Yes
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by mcrozes** [comment]
Hello @nfahlgren -

I am reviewing the your PR and will merge it as soon as it clears our CI/CD pipeline.

**Comment by mcrozes** [comment]
2.7.4 has been released today. Thanks for your contribution.
