### ISSUE TITLE
"My Files" Section of the web interface crashing regularly.

### ISSUE THREAD

**Issue by albjoao** [awslabs/scale-out-computing-on-aws#85]
Current Version:
2.6.0

Issue:
On our deployed instance, the "My Files" section of the website regularly goes down (502 bad gateway error). When this occurs the other parts of the user interface are still available but users are not able to view their files or submit batch submissions.

The main errors I see in the log files are the following:

In uwsgi.log:

`
Job "schedule_auto_stop (trigger: interval[0:05:00], next run at: 2023-01-26 13:33:02 UTC)" raised an exception
Traceback (most recent call last):
  File "/apps/soca/soca-supernova-r3-1/python/3.7.1/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "./scheduled_tasks/manage_dcv_instances_lifecycle.py", line 481, in schedule_auto_stop
    windows_auto_stop_instance(instances_ids_to_check)
  File "./scheduled_tasks/manage_dcv_instances_lifecycle.py", line 235, in windows_auto_stop_instance
    logger.error("windows_auto_stop_instance: SSM failed for {} with ssm_id {}".format(instance_id, ssm_command_id))
UnboundLocalError: local variable 'ssm_command_id' referenced before assignment
`

and in both the api/application logs the main error that appears is the following:

`requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

**Comment by FranklinMoux** [comment]
The error message in the uwsgi.log file suggests that there is an unbound local variable 'ssm_command_id' being referenced before it is assigned a value. This is causing the "windows_auto_stop_instance" function to raise an exception and preventing it from executing the auto stop of the instances.

In the api/application logs, the error message suggests that there is a connection error when trying to establish a connection to a remote server.

To fix this issue, you can try the following steps:
1. Review the "windows_auto_stop_instance" function and ensure that the variable 'ssm_command_id' is being assigned a value before it is being used.
2. Check if the instances being checked for auto stop are still running and if they are, ensure that they are in the correct state before trying to stop them.
3. Check the Network connection between the deployed instance and the remote server that it is trying to connect to. Make sure that there are no firewalls or security groups blocking the connection.
4. Check that the endpoint url is correct
5. Check the credential used to connect to the remote server are still valid.

**Comment by mcrozes** [comment]
Hello,

Sorry for the late reply. I'm now back to support the original SOCA codebase again, are you still experiencing this issue? I'm currently reviewing all open PR/Issue to address them in the future release.

**Comment by mcrozes** [comment]
Closing ticket. Feel free to re-open if needed.
