### ISSUE TITLE
RHEL8 desktop support

### ISSUE THREAD

**Issue by parenthalpy** [awslabs/scale-out-computing-on-aws#89]
**Describe the feature you'd like**
My team would really like to have RHEL8 desktops via SOCA, but the web interface only supports RHEL7. Can you provide some pointers on what would be required for RHEL8 support?

**Additional context**
![image](https://user-images.githubusercontent.com/128624210/226972779-1b367c5d-5dcc-4e78-841e-aca9db0bb540.png)

**Comment by mission-coliveros** [comment]
Any updates on this?

**Comment by mcrozes** [comment]
Hello, sorry for the delay. New version of SOCA will support the following OS for both VDI and Compute:

1. RHEL7
2. RHEL8
3. RHEL9
4. Rocky8
5. Rocky9
6. Centos7
7. ALI2
8. ALI2023

Feel free to email me if you want further details
