### ISSUE TITLE
Scheduler instance requires IMDSv1 to be enabled 

### ISSUE THREAD

**Issue by WayneStallwood** [awslabs/scale-out-computing-on-aws#97]
**Describe the bug**
The Scheduler instance makes IMDS calls with no token (as evidenced by monitoring the MetadataNoToken CW metric) and is deployed with IMDSv1 enabled (IMDSv2 not enforced) 

**To Reproduce**
Deploy SOCA and verify the IMDS settings for the Scheduler instance(s), monitor the CW Metric for MetadataNoToken to see calls with no token

**Expected behavior**
Scheduler instance should be deployed with IMDSv2 enforced and make tokenized calls to IMDS to be compliant with security recommendations and standards, several account level security scan tools will flag this as non-compliant

**Please complete the following information about the solution:**
- [ ] Version: v2.7.4

**Comment by mcrozes** [comment]
Hello @WayneStallwood  -

Correct, this flag (https://github.com/awslabs/scale-out-computing-on-aws/blob/main/installer/default_config.yml#L6) only apply to ComputeNode. I will review it and ensure it's also applied during the scheduler instance creation (https://github.com/awslabs/scale-out-computing-on-aws/blob/main/installer/resources/src/cdk_construct.py#L1245).

Thank for reporting this bug.

**Comment by mcrozes** [comment]
Hello,

We are now enforcing IMDSv2 for the scheduler per https://github.com/awslabs/scale-out-computing-on-aws/commit/e1617b14bb1b4a29a5bc6e02fa76c1312a333389
